name: Check types

on: workflow_call

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: ./github/actions/install.yml

    - name: Check types
      shell: bash
      run: yarn check-types
