name: Build

on: workflow_call

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./github/actions/install.yml

      - name: Run linter
        run: yarn lint
