name: Lint

on: workflow_call

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: ./github/actions/install.yml

    - name: Run linter
      shell: bash
      run: yarn lint
