name: Main branch workflow

on:
  push:
    branches: ['*']
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/preparation.yml

  type-check:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/type-check.yml

  unit-tests:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/type-check.yml
