name: Main branch workflow

on:
  push:
    branches: ['*']
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  prepare:
    uses: ./.github/workflows/preparation.yml

  type-check:
    needs: prepare
    uses: ./.github/workflows/type-check.yml

  unit-tests:
    needs: prepare
    uses: ./.github/workflows/unit-tests.yml
