name: PR workflow

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install

      - uses: ./.github/actions/lint

      - uses: ./.github/actions/type-check

      - uses: ./.github/actions/test

      - uses: ./.github/actions/build
