name: Preparation

on: workflow_call

jobs:
  preparation:
    name: Preparation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./github/workflows/setup-node.yml

      - name: Set environment variables
        shell: bash
        run: mv .env.example .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
